# Generated by Django 4.2.17 on 2025-04-15 21:25

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('todo', '0002_chat'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Chat',
            new_name='ChatWithAI',
        ),
    ]
