# Generated by Django 4.2.17 on 2025-04-16 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_alter_chatwithai_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatwithai',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
