# Generated by Django 4.2.17 on 2025-04-16 02:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0007_alter_chatwithai_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatwithai',
            old_name='response',
            new_name='ai_response',
        ),
    ]
