# Generated by Django 4.2.17 on 2025-01-16 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_profile_avatar"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="avatar",
            field=models.ImageField(default="1.png", upload_to="profile_avatars"),
        ),
    ]
